<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <UcadVersion>$([System.IO.File]::ReadAllText('$(MSBuildThisFileDirectory)VERSION').Trim())</UcadVersion>
    <Version>$(UcadVersion)</Version>
    <VersionPrefix>$(UcadVersion)</VersionPrefix>
    <AssemblyVersion>$(UcadVersion).0</AssemblyVersion>
    <FileVersion>$(UcadVersion).0</FileVersion>
    <InformationalVersion>$(UcadVersion)</InformationalVersion>
  </PropertyGroup>
</Project>
